[package]
name = "robo"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.30.0", default-features = false, features = ["accesskit", "default_fonts", "glow"] }
ollama-rs = "0.2.2"
dirs = "5.0.1"
bincode = "1.3.3"
serde = "1.0.217"
thiserror = "2.0.11"
clap = { version = "4.5.18", features = ["derive"] }
winapi = { version = "0.3.9", features = ["wincon"] }

[profile.release]
codegen-units = 1
panic = "abort"
opt-level = "s"
lto = true
strip = true
