# WARNING: DO NOT USE THIS FILE IN PROD
# PORTS ARE EXPOSED FOR DEVELOPMENT PURPOSES

name: robo-dev

volumes:
  pgdata1:
  pgdata2:
  ollama:

services:
  # APP service
  app:
    image: robo-core:latest

    environment:
      - OLLAMA_URL=http://ollama_balancer:8080

      - PG_SHARD1=postgres://postgres:postgress@postgres1:5432/postgres
      - PG_SHARD2=postgres://postgres:postgress@postgres2:5432/postgres

      - REDIS_URL=redis://redis:6379

      - JWT_SECRET=jwt_secret

    build:
      context: ../../
      dockerfile: ./.docker/dev/Dockerfile

    ports: [3000:3000]

    depends_on: [postgres1, postgres2, redis, ollama_balancer]

  # postgres shards are not replicated because they must use different volumes
  # POSTGRES shard 1
  postgres1:
    image: postgres:17.2-alpine
    shm_size: 128mb

    ports: [5433:5432] # HIDE IN PROD

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgres

    volumes: [pgdata1:/var/lib/postgresql/data]

  # POSTGRES shard 2
  postgres2:
    image: postgres:17.2-alpine
    shm_size: 128mb

    ports: [5434:5432] # HIDE IN PROD

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgres

    volumes: [pgdata2:/var/lib/postgresql/data]

  # REDIS service
  redis:
    image: redis:7.4-alpine

    ports: [6379:6379] # HIDE IN PROD

  # OLLAMA load balancer
  ollama_balancer:
    image: nginx:mainline-alpine

    volumes: [./ollama.nginx.conf:/etc/nginx/nginx.conf:ro]

    ports: [8080:8080] # HIDE IN PROD

    depends_on: [ollama]

  # OLLAMA service
  ollama:
    image: ollama/ollama:latest

    volumes: [ollama:/root/.ollama]

    deploy:
      mode: replicated
      replicas: 2

      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
