# WARNING: DO NOT USE THIS FILE IN PROD
# PORTS ARE EXPOSED FOR DEVELOPMENT PURPOSES

name: robo-dev

volumes:
  pgdata:
  ollama:

services:
  # APP service
  app:
    image: robo-core:latest
    restart: always

    environment:
      - OLLAMA_URL=http://ollama_balancer:8080
      - POSTGRES_URL=postgres://postgres:postgress@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379

    build:
      context: ../../
      dockerfile: ./.docker/dev/Dockerfile

    ports: [3000:3000]

    depends_on: [postgres, redis, ollama_balancer]

  # POSTGRES service
  postgres:
    image: postgres:17.2-alpine
    restart: always
    shm_size: 128mb

    ports: [5433:5432] # HIDE IN PROD

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgres

    volumes: [pgdata:/var/lib/postgresql/data]

  # REDIS service
  redis:
    image: redis:7.4-alpine
    restart: always

    ports: [6379:6379] # HIDE IN PROD

  # OLLAMA load balancer
  ollama_balancer:
    image: nginx:mainline-alpine
    restart: always

    volumes: [./ollama.nginx.conf:/etc/nginx/nginx.conf:ro]

    ports: [8080:8080] # HIDE IN PROD

    depends_on: [ollama]

  # OLLAMA service
  ollama:
    image: ollama/ollama:latest
    restart: always

    volumes: [ollama:/root/.ollama]

    deploy:
      mode: replicated
      replicas: 2

      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
