name: Check code quality

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  check-linting:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check clippy
        run: cargo clippy -- -D warnings

      - name: Check fmt
        run: cargo fmt -- --check
