name: Check code quality

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  check-linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # install rust
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          toolchain: nightly

      - name: Check clippy
        run: cargo clippy -- -D warnings
      - name: Check fmt
        run: cargo fmt -- --check
